### ISSUE TITLE
SDF calculation

### ISSUE THREAD

**Issue by rykawamura** [craigleili/GenZI#2]
Hello, thank you for your great work.
I am looking for code to calculate SDF. Do you have any plans to share the code, or would you mind letting me know the library you used?

Best,

**Comment by craigleili** [comment]
Hello,
We first computed a UDF for the scene and then used [kaolin](https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.mesh.html#kaolin.ops.mesh.check_sign) to compute the signs.

Best,
Lei

**Comment by rykawamura** [comment]
Thank you so much! Let me close this question.
